### PR TITLE
Submit here

### PR DESCRIPTION
**Pull request by gloriousgeneralist**
@codeocelot This is looking better! I just wanted to check--no matter what search I do, I get the message 

"Visualize your research with a Knowledge Map and make unexpected connections. Click here and use Yewno Discover to carry out your research more efficiently and find links to relevant high quality documents. Yewno Discover can help you with topic exploration, hypothesis creation, and redirect research that has reached a dead end."

Is that expected?

### CODE REVIEW

**Comment by codeocelot** [comment]
Hi @gloriousgeneralist yup, that copy should be shown.  The end result should look like this screenshot (please let me know if it doesn't!):

Screen Shot 2020-07-23 at 3 21 11 PM

**Comment by cbyewno** [comment]
@gloriousgeneralist Please advise when this might be available on PrimoSTudio to select as an Addon for Primo users. Thank you so much

**Comment by gloriousgeneralist** [comment]
@codeocelot I had the text show up, but no image. 

> 
> Hi @gloriousgeneralist yup, that copy should be shown. The end result should look like this screenshot (please let me know if it doesn't!):
> 
> Screen Shot 2020-07-23 at 3 21 11 PM

**Comment by codeocelot** [comment]
😔. @gloriousgeneralist are there any errors in your devtool console?

**Comment by gloriousgeneralist** [comment]
> 
> 
> 😔. @gloriousgeneralist are there any errors in your devtool console?

Oh pretty straightforward problem luckily. The error is invalid product key. I was using the one from the summer that was sent to Matt. Guess I need a new one.l

**Comment by codeocelot** [comment]
Hi @gloriousgeneralist I was thinking that could have been the case! Do you have an email where I can send you one?

**Comment by gloriousgeneralist** [comment]
> 
> 
> Hi @gloriousgeneralist I was thinking that could have been the case! Do you have an email where I can send you one?

Sure, margaret.heller@gmail.com

**Comment by gloriousgeneralist** [comment]
This is working now.

**Comment by cbyewno** [comment]
@gloriousgeneralist Thank you so much.  Is this available for Primo Studio users now as a selection?

**Comment by gloriousgeneralist** [comment]
It's now available in Primo Studio as of a few minutes ago.

**Comment by cbyewno** [comment]
Thank you for all your hard work on this.  WE very much appreciate it.


* Kind Regards, Carola*

*[image: Yewno Logo] Carola Blackwood Customer Account Manager - Education
carola@yewno.com <carola@yewno.com> 561-908-4916 yewno.com
<https://yewno.com/>*

**Pull request merged**
