### PR TITLE
verify Yewno edits in dev

### PR DESCRIPTION
**Pull request by gloriousgeneralist**
This includes some updates that Yewno has submitted. Needs a check on submit_here branch in Primo Studio.

### CODE REVIEW

**Review by MblackUC — COMMENTED** [review]
I have installed the updated add on the submit_here branch. It seems to install but requests a product key. The previous keys don't seem to work.

**Comment by cbyewno** [comment]
I will request a new product key.


* Kind Regards, Carola*

*[image: Yewno Logo] Carola Blackwood Customer Account Manager - Education
carola@yewno.com <carola@yewno.com> 561-908-4916 yewno.com
<https://yewno.com/>*

**Comment by cbyewno** [comment]
Please see comments from our engineering team regarding inability to use
the API key we sent you: " Existing API keys for Primo Addon are active,
for example primo_qZuQd3nQ , so creating new ones would not solve this
issue. Also we are pretty sure that the issue is not related to last
changes we made so if Primo staff confirms that mentioned primo_qZuQd3nQ key
does not work could they provide us with more details about the error, for
example, are there any errors in devtool console?"


* Kind Regards, Carola*

*[image: Yewno Logo] Carola Blackwood Customer Account Manager - Education
carola@yewno.com <carola@yewno.com> 561-908-4916 yewno.com
<https://yewno.com/>*

**Comment by MblackUC** [comment]
Thank you. I had an older product key and not primo_qZuQd3nQ . I have tried again with primo_qZuQd3nQ  and it seemed to install. 

Thank you,
Matt

**Review by MblackUC — APPROVED** [review]

**Comment by cbyewno** [comment]
Thank you.  Can you advise when action is completed and users can view changes? Thank you

**Comment by MblackUC** [comment]
I have merged the request to dev. I believe one other person will confirm that it works and they will push it to the master branch.

Thank you,
Matt

**Pull request merged**
