### PR TITLE
Add primo-studio-appointment-scheduler

### PR DESCRIPTION
**Pull request by jweisman**

### CODE REVIEW

**Comment by gloriousgeneralist** [comment]
@jweisman since this is still marked as draft are you ready for us to test?

**Comment by jweisman** [comment]
Hi @gloriousgeneralist - thanks for asking. Still testing for now. I'll change the status to "ready for review" when the testing is completed.

**Comment by jweisman** [comment]
Hi @gloriousgeneralist - all set now (I hope : ). Ready for review.

Thanks.

**Comment by jweisman** [comment]
Just wanted to ping to see if there was anything else you need from me....

**Pull request merged**
