### PR TITLE
feat(update addon): update yewno addon to v0.0.6

### PR DESCRIPTION
**Pull request by codeocelot**
Hi @gloriousgeneralist we'd like to submit an update to our previous addon originally submitted in PR #55.  Our updated addon supports more features, but otherwise is substantially similar to the previous submission.

### CODE REVIEW

**Comment by gloriousgeneralist** [comment]
Hi @codeocelot some new reviewers are coming on and learning the process, so it may take a few days to get them settled, but we will have it up soon.

**Comment by cbyewno** [comment]
Hello Margaret, thanks for the update.  Can you tell me a timeframe for
"soon"?  Might that be the end of the week?  Thanks so much.


* Kind Regards, Carola*

*[image: Yewno Logo] Carola Blackwood Customer Account Manager - Education
carola@yewno.com <carola@yewno.com> 561-908-4916 yewno.com
<https://yewno.com/>*

**Comment by cbyewno** [comment]
Herzlichen Dank, Ulrich


* Kind Regards, Carola*

*[image: Yewno Logo] Carola Blackwood Customer Account Manager - Education
carola@yewno.com <carola@yewno.com> 561-908-4916 yewno.com
<https://yewno.com/>*

**Comment by cbyewno** [comment]
> Hi @codeocelot some new reviewers are coming on and learning the process, so it may take a few days to get them settled, but we will have it up soon.

Hi @gloriousgeneralist - can you give us an update on completion by your team?  An ETA would be great so we can move the marketing messages forward. Thank you

**Comment by gloriousgeneralist** [comment]
We will get it done today--I'm sorry for the delay.

**Comment by cbyewno** [comment]
@gloriousgeneralist Will this addon immediately show up in the Primo Studio toolbox, or will there be an additional step involved there? Thanks so much

**Comment by gloriousgeneralist** [comment]
It will, it just needs to be moved to the right branch.

Margaret

**Comment by cbyewno** [comment]
Who moves it to the right branch?


* Kind Regards, Carola*

*[image: Yewno Logo] Carola Blackwood Customer Account Manager - Education
carola@yewno.com <carola@yewno.com> 561-908-4916 yewno.com
<https://yewno.com/>*

**Comment by MblackUC** [comment]
Hello,

I'm just working on reviewing and merging the pull request with dev. It looks like I need a Yewno product key to test it in Primo Studio. Could you provide that to me? 

Thank you

**Comment by cbyewno** [comment]
@MblackUC Is the review complete?  Is this addon now visible to  customers using Primo Studio?

**Comment by cbyewno** [comment]
@gloriousgeneralist Can you please advise on status of this Addon?  When can customers view it in Primo Studio? Thank you

**Comment by uleodolter** [comment]
@cbyewno please see my comment in #60 

actually you can test i after starting primo studio by adding `&branch=dev`  to browser url.  this way you access features.json from dev branch.   but it was not able to successfully test it.   could you please try ?   it think to the hook option in features.json needs to dash-style and not CamelCase.

**Comment by codeocelot** [comment]
Hi @uleodolter yes, I can see the hook format doesn't match the rest of the entries in `features.json`. Should I open another PR to update this value to kebab-case (`prm-back-to-library-search-button-after`)? Unfortunately we don't have a primo studio deployment of our own, so our ability to test this on our own is limited.

**Comment by cbyewno** [comment]
@uleodolter @gloriousgeneralist please advise on next steps.  Should we open another PR?  Thank you

**Comment by gloriousgeneralist** [comment]
Yes I think so, thanks.

**Comment by cbyewno** [comment]
https://github.com/primousers/primostudio/pull/61
We just added it. Please check and let me know if there is any problem, as
we don't have an environment in which to test this. Thanks so much.
 Kind Regards,


* Carola*

*[image: Yewno Logo] Carola Blackwood Customer Account Manager - Education
carola@yewno.com <carola@yewno.com> 561-908-4916 yewno.com
<https://yewno.com/>*

**Comment by cbyewno** [comment]
@gloriousgeneralist @MblackUC @uleodolter Can you please review pull #61 which was uploaded two days ago.

**Comment by cbyewno** [comment]
Hi Margaret, we have added a pull request to our Primo Addon .  Can you
please test and advise on modifications needed? Thank you so much.
https://github.com/primousers/primostudio/pull/63

  Kind Regards,


* Carola*

*[image: Yewno Logo] Carola Blackwood Customer Account Manager - Education
carola@yewno.com <carola@yewno.com> 561-908-4916 yewno.com
<https://yewno.com/>*

**Pull request merged**
