### PR TITLE
feat(update addon): update yewno addon to v0.0.6, w/ kebab hook

### PR DESCRIPTION
**Pull request by codeocelot**
update yewno primo addon to v0.0.6, using kebab-case hook

### CODE REVIEW

**Comment by cbyewno** [comment]
@gloriousgeneralist can you please get this reviewed. Thank you.

**Comment by gloriousgeneralist** [comment]
> 
> 
> @gloriousgeneralist can you please get this reviewed. Thank you.

Will try to get to this today--I apologize, but we are all volunteers and it's been a very busy period.

**Comment by cbyewno** [comment]
@gloriousgeneralist   Can you please assign this to be reviewed.  Thank you so much.  @codeocelot fyi

**Comment by gloriousgeneralist** [comment]
@codeocelot I merged this to test it in Primo Studio, but it doesn't seem to install correctly. I see <@yewno/primo-addon parent-ctrl="$ctrl.parentCtrl"> rather than the graph.

**Pull request merged**
