### PR TITLE
Submit here

### PR DESCRIPTION
**Pull request by gloriousgeneralist**
This installs fine. @jweisman I see this error, I assume because I don't have the corresponding Alma app set up?
image

### CODE REVIEW

**Comment by gloriousgeneralist** [comment]
@MblackUC do you want to double check and merge?

**Comment by jweisman** [comment]
Hi @gloriousgeneralist - either that or the API key you provided in the configuration isn’t set up right so the service can’t authenticate. Do you want to share the URL of the Primo environment you’re testing in so I can double-check?

**Comment by MblackUC** [comment]
Hi Margaret,

I have a pretty busy afternoon of meetings but I can take a look at this evening.

Thanks,
Matt

**Comment by gloriousgeneralist** [comment]
@jweisman Sure, I've been working with https://luc.primo.exlibrisgroup.com. I created the API key with Primo Public-Key - Production Read-only. The thing I'm not sure about is that to log in I have to do the email login option since my institutional SSO won't work on Primo Studio, so to actually test it I end up at http://primo-studio.exlibrisgroup.com/discovery/account?vid=01LUC_INST:01LUC&section=overview&lang=en.

**Comment by MblackUC** [comment]
I was able to install the add on using a API key with Primo Public-Key - Production Read-only too. I have the same issue with not being able to login since our institutional SSO won't work with Primo Studio.

**Comment by jweisman** [comment]
Hi @gloriousgeneralist - looks like there was an issue with the service authentication for some instances. I believe it's been resolved. Can you check again? Thanks.

@MblackUC - this will likely only work for Primo VE.

**Comment by gloriousgeneralist** [comment]
Just checked again, and I don't see that error, so I think it's ok now.

**Comment by jweisman** [comment]
Thanks!

**Pull request merged**
